{ "links" : {
	"ny craigslist": "http://newyork.craigslist.org/search/nfa/mnh?query=fios&srchType=A&minAsk=&maxAsk=&bedrooms=&nh=134&nh=137&nh=128",
	"ny craig all": "http://newyork.craigslist.org/search/nfa/mnh?query=fios&srchType=A&minAsk=&maxAsk=&bedrooms=",
	"PROP Jakobsen": "http://www.nofeerentals.com/apartments.asp",
	"PROP jr": "https://www134.safesecureweb.com/jrproperties/10.html",
	"PROP abington": "http://www.abingtonproperties.com/",
	"PROP b&l w": "http://www.bandlmanagement.com/Search/Building/434-W-19th-St.htm",
	"PROP bettina": "http://www.bettinaequities.com/",
	"PROP align": "http://www.alginny.com/searchapp.php",
	"PROP rose": "http://www.rosenycapts.com/SearchResults.aspx?Type=2&Neighborhood=&AptSize=&Amenities=&MinPrice=&MaxPrice=",
	"dsa": "http://www.dsarealty.com/search.aspx",
	"halstead": "http://www.halstead.com/rental/",
	"paige": "http://pageapts.com/",
	"gatsby*": "http://gatsbyrealty.com/",
	"point": "http://point-nyc.com/",
	"caliber": "http://www.calibernyc.com/nyc_apartments.htm",
	"key ny": "http://keynewyork.com/",
	"kvny": "http://www.kvny.com/index.cfm?page=search&sub=Rentals",
	"spire": "http://www.spiregroupny.com/default.aspx",
	"pinkston*": "http://pinkstonerealty.com/",
	"eastpoint": "http://www.eastpointeproperties.com/home.html",
	"hecht": "http://www.hechtgroup.com/",
	"landmark": "http://www.nycapartmentsource.com/",
	"alpha": "http://www.alphanyc.com/",
	"citi habitat": "http://www.citi-habitats.com/",
	"mns*": "http://www.mns.com/advanced_search/rentals",
	"domain prop": "http://www.domain-properties.com/",
	"ccny": "http://www.ccrny.com/",
	"related": "http://www.related.com/Rentals/",
	"FIOS": "http://www.verizon.com/FiOS"
	}
}