{ "links" : [
		{
			"hockey": {
				"http://nhl.com": "^nhl.com",
				"http://www.nhl.com/ice/scores.htm": "**scores",
				"http://hockey.fantasysports.yahoo.com/hockey/60024/1": "fantasy",
				"http://www.sportsnet.ca/hockey/nhl/nhl-line-combo-central-2013-14/": "line combos",
				"http://tsn.ca/nhl": "tsn.ca",
				"http://www.nhl.com/startinggoalies/": "starting goal",
				"http://www.nicetimeonice.com/": "toi",
				"http://war-on-ice.com/gametable.html": "war on ice",
				"http://hockeystats.ca/": "hockeystats",
				"http://www.sportingcharts.com/": "sporting charts",
				"http://somekindofninja.com/nhl/": "ninja",
				"http://www.naturalstattrick.com/": "stat trick",
				"http://hockeyanalysis.com/": "hockeyanalysis"
			},
			"baseball": {
				"http://www.baseballprospectus.com/": "bp",
				"http://mlb.mlb.com/": "^mlb.com",
				"http://m.mlb.com/tv/": "*tv",
				"http://m.mlb.com/network/live?mso_id=Verizon": "*net",
				"http://sports.yahoo.com/mlb/": "^yahoo",
				"http://espn.go.com/mlb/scoreboard": "*scores",
				"http://baseball.fantasysports.yahoo.com/b1": "^fantasy",
				"http://baseball.fantasysports.yahoo.com/b1/36627/2": "**hcbl",
				"http://m-abl.baseball.cbssports.com/": "^mabl",
				"http://m-abl.baseball.cbssports.com/stats/stats-main": "**players",
				"http://m-abl.baseball.cbssports.com/teams": "**roster",
				"http://m-abl.baseball.cbssports.com/scoring/standard": "**live",
				"http://games.espn.go.com/flb/leagueoffice?leagueId=242&teamId=4&seasonId=2016": "^espn",
				"http://games.espn.go.com/flb/clubhouse?leagueId=242&teamId=4&seasonId=2016": "*live",
				"http://www.mlb.com/mlb/fantasy/news/": "mlb fantasy",
				"http://www.foxsports.com/mlb/just-a-bit-outside": "fox outside",
				"http://mlbdepthcharts.com": "depth charts",
				"http://nbcsportsradio.com/": "nbc radio",
				"http://www.rotoworld.com/playernews/mlb/baseball-player-news": "rotoworld",
				"http://baseballsavant.com/index.php": "savant",
				"http://espn.go.com/mlb/stats/fielding/_/position/c/sort/catcherStolenBasesAllowed/qualified/false/order/false": "catcherSBs",
				"http://mlb.mlb.com/news/probable_pitchers/?tcid=nav_mlb_schedule": "SPs",
				"http://espn.go.com/mlb/stats/parkfactor": "park factor",
				"http://www.covers.com/sports/mlb/matchups": "covers matchups",
				"http://www.fangraphs.com/": "fangraphs",
				"https://ballsandstrikes.co/": "ballsandstrikes"
			},
			"football": {
				"http://www.nfl.com/news/around-the-league": "nfl greg",
				"http://deadspin.com/": "deadspin",
				"https://gamerewind.nfl.com/nflgr/secure/schedule": "rewind",
				"http://ca.sports.yahoo.com/nfl/": "^yahoo",
				"http://ca.sports.yahoo.com/nfl/scoreboard": "*scores",
				"http://football.fantasysports.yahoo.com/": "fantasy",
				"http://games.espn.go.com/ffl/clubhouse?leagueId=1381405&teamId=14&seasonId=2015": "espn",
				"http://www.footballoutsiders.com/": "fo",
				"http://www.footballoutsiders.com/stats/snapcounts": "^snaps",
				"http://www.grantland.com/": "grantland",
				"http://profootballtalk.nbcsports.com/": "pft",
				"http://www.profootballweekly.com/": "pfweek",
				"http://smartfootball.com/": "smart",
				"http://www.borischen.co/": "borischen",
				"http://games.espn.go.com/ffl/pointsagainst": "espn ffpa",
				"http://subscribers.footballguys.com/apps/news.php": "fguys",
				"http://forums.footballguys.com/forum/index.php?s=2bc00ce9facf1f0a805aa565ead01549&showtopic=713437": "^idp",
				"http://sportsfrog.net": "sportsfrog",
				"http://sports.yahoo.com/college-football/": "^yahoo",
				"http://espn.go.com/college-football/scoreboard/_/group/80/": "*scores",
				"http://football.fantasysports.yahoo.com/college/7067/6": "fantasy"
			},
			"google": {
				"https://www.google.com/about/careers/students/guide-to-technical-development.html": "tech dev",
				"https://gmail.google.com/": "^gmail",
				"https://mail.google.com/mail/u/0/h/": "*html email",
				"http://m.gmail.com/": "*mobile email",
				"https://google.com/": "search", 
				"https://plus.google.com/": "google +",
				"https://plus.google.com/photos/yourphotos": "photos",
				"http://www.google.com/reader/": "reader",
				"https://www.google.com/voice/": "voice",
				"http://www.google.com/calendar/": "calendar",
				"http://drive.google.com/": "docs",
				"http://maps.google.com/": "maps",
				"https://www.google.com/analytics/web/?hl=en": "^analytics",
				"https://analytics.google.com/analytics/web/?hl=en#report/defaultid/a439245w47564276p47906572/": "*j",
				"https://www.google.com/admanager/": "ad manager",
				"https://www.google.com/adxseller/adx/app#home": "adx",
				"http://youtube.com/": "youtube",
				"http://translate.google.com/": "translate",
				"https://domains.google.com": "domains",
				"https://developers.google.com/speed/pagespeed/insights/": "dev insights",
				"https://www.google.com/edu/tools-and-solutions/guide-for-technical-development/": "education",
				"https://developers.google.com/speed/pagespeed/insights/": "page speed",
				"https://www.google.com/webmasters/tools/home?hl=en": "web tools",
				"https://developers.google.com/webmasters/structured-data/customize/social-profiles": "social profiles",
				"https://developers.google.com/webmasters/structured-data/testing-tool/": "data testing",
				"https://partnerdash.google.com/partnerdash/d/news": "news dash",
				"https://accounts.google.com/IssuedAuthSubTokens": "two factor",
				"https://admin.google.com/AdminHome": "apps dash",
	    		"https://www.google.com/dashboard/b/0/?hl=en-US&pli=1": "dash"
	    	},
	    	"digital": {
	    		"https://app.groupme.com/chats": "groupme",
				"https://github.com/oiler?tab=repositories": "github",
	    		"https://digg.com/reader/folder/New%20Feeds": "reader",
	    		"http://cloud.feedly.com/#category%2FNew%20Feeds": "feedly",
				"https://twitter.com/search-advanced?lang=en": "tw adv search",
				"https://www.twitter.com/": "twitter",
				"https://twitter.com/#!/oiler/lists": "^lists",
				"https://twitter.com/#!/oiler/cfb": "**cfb list",
				"https://twitter.com/#!/oiler/hockey": "**hockey list", 
				"https://twitter.com/#!/oiler/football": "**football list",
				"https://twitter.com/#!/oiler/baseball": "**baseball list",
				"https://twitter.com/#!/oiler/favorites": "*favorites",
				"http://vellum.nytlabs.com/mylinks": "vellum links",
				"http://ssl.facebook.com/": "^facebook",
				"http://m.facebook.com/": "*mobile fb",
				"http://about.me": "about.me",
				"http://www.tumblr.com/dashboard": "tumblr",
				"http://getpocket.com/a/queue/list/": "pocket",
				"http://www.instapaper.com/u": "instapaper",
				"https://wwws.mint.com/overview.event": "mint",
				"http://bit.ly/": "bit.ly",
				"http://dropbox.com": "dropbox",
				"https://foursquare.com/": "foursquare",
				"http://www.reddit.com/r/all/": "reddit",
				"http://oiler2.wordpress.com/wp-admin/": "wp",
				"https://www.formstack.com/admin/form/dashboard": "formstack",
				"https://console.aws.amazon.com/s3/home": "aws",
				"http://ifttt.com/dashboard": "ifttt",
				"http://getprismatic.com/newsfeed#": "prismatic",
				"http://oiler.phpfogapp.com": "thinkup",
				"http://hellofax.com": "hellofax",
				"https://foxlab.harvestapp.com/invoices?tab=open": "harvest",
				"http://www.trillian.im/chat": "trillian",
				"https://dashboard.getpantheon.com/": "pantheon",
				"https://trello.com/b/liWFfixx/oiler-fresh": "trello",
				"https://www.google.com/search?q=my+ip": "my ip"
			},
			"news": {
				"http://nytimes.com/": "nytimes",
				"http://www.wnyc.org/": "wnyc",
				"http://www.npr.org/": "npr",
				"http://propublica.org": "propublica",
				"http://twit.tv/": "^twit", 
				"http://live.twit.tv/": "*live",
				"http://www.opensecrets.org/index.php": "opensecrets"
			},
			"stream": {
				"https://play.pocketcasts.com/web#/podcasts/new_releases": "pocketcasts",
				"http://netflix.com/": "netflix",
				"http://espn.go.com/watchespn/": "espn",
				"http://pandora.com/": "pandora",
				"http://watch.slingbox.com/": "sling",
				"http://www.tnt.tv/video/?cid=61779": "tnt",
				"http://www.hulu.com/the-colbert-report": "colbert report",
				"http://www.hulu.com/the-daily-show-with-jon-stewart": "the daily show",
				"http://www.cbc.ca/sports/hockeynightincanada/video/": "hnic",
				"https://www.amazon.com/gp/video/library": "amazon",
				"http://hulu.com": "hulu",
				"http://hbogo.com": "hbogo",
				"http://www.cbsnews.com/sections/60minutes/main3415.shtml": "60 minutes"
			},
			"dev": {
				"http://screensiz.es/": "screensiz.es",
				"http://jsonlint.com/": "jsonlint",
				"http://www.webpagetest.org/": "webpagetest",
				"http://code.google.com/speed/page-speed/docs/rules_intro.html": "page speed",
				"http://centralops.net/co/": "centralops",
				"http://mxtoolbox.com/": "mxtoolbox",
				"http://validator.w3.org/": "W3C Validator",
				"http://www.nikmakris.com/images/blog/webding_characters.gif": "webdings",
				"http://www.pctools.com/guides/password/?length=24&phonetic=on&alpha=on&mixedcase=on&numeric=on&punctuation=on&nosimilar=on&quantity=9&generate=true#password_generator": "password gen",
				"http://html5boilerplate.com/": "html5 plate",
				"http://html5rocks.com/": "html5 rocks",
				"http://www.initializr.com/": "initalizer",
				"http://jsfiddle.net/": "jsfiddle",
				"http://jsonviewer.stack.hu/": "json viewer",
				"http://charactercounttool.com/": "char count",
				"http://jhy.io/tools/convert-word-to-plain-text": "word to text",
				"http://appinventor.mit.edu/": "app inventor",
				"http://javascript.crockford.com/": "d crockford",
				"https://github.com/jshomes/learning-resources": "jshomes resources",
				"https://kangax.github.io/compat-table/es6/": "es6 compat",
				"https://blog.jacius.info/git-submodule-cheat-sheet/": "git modules",
				"http://tmpvar.com/markdown.html": "git markdown preview",
				"https://medium.com/javascript-scene": "js scene"
			},
			"money": {
				"https://www.suncoastcreditunion.com/": "ssfcu",
				"https://www.bankofamerica.com/index.jsp?page_msg=mbna": "mbna",
				"https://www.americanexpress.com/": "amex",
				"https://www.barclaycardus.com/": "barclays",
				"https://chaseonline.chase.com/": "chase",
				"http://verizon.com/myverizon": "verizon"
			},
			"other": {
				"https://venues.chelseapiers.com/sportmgr/index.cfm?fuseaction=division.home&division_id=2088": "chelseapiers",
				"https://venues.chelseapiers.com/sportmgr/index.cfm?fuseaction=team.home&team_id=16400": "icedogs",
				"https://venues.chelseapiers.com/sportmgr/index.cfm?fuseaction=team.home&team_id=16420": "lg",
				"http://www.chelseapiers.com/sc/club/index.cfm": "club",
				"http://www.zogsports.com/nyc/Home.aspx": "zogsports",
				"http://randallsisland.org/wordpress/wp-content/uploads/2010/04/RI-Bronx-Shore-Existing-Fields-No-Orientation-signs.pdf": "zog map",
				"http://newyork.craigslist.org/mnh/": "ny craigslist",
				"http://tampa.craigslist.org/": "tb craigslist",
				"http://tv.yahoo.com/grid?lineup=us_DITV539&genres=&all=1&dur=&starttime=&starthour=&startdate=&.intl=us": "tv",
				"https://mail.yahoo.com": "yahoo",
				"http://mailinator.com/": "dodgeit",
				"http://www.indeed.com/": "indeed",
				"http://www.simplyhired.com/": "simplyhired",
				"http://jobs.wordpress.net/": "wp jobs",
				"http://dice.com/": "dice.com",
				"http://www.techmeme.com/events": "techmeme events",
				"http://www.teamworkonline.com/xjobs.cfm?location=&s=&Category=WebCreativeServices&button.x=104&button.y=21&button=Submit": "^twork",
				"http://hockeyjobs.nhl.com/teamwork/jobs/jobs.cfm/Communications?supcat=214": "**comm",
				"http://hockeyjobs.nhl.com/teamwork/jobs/jobs.cfm/Technical-Services?supcat=224": "**tech",
				"http://newyork.craigslist.org/": "craigslist",
				"http://www.showclix.com/event/3915161": "fallon tix",
				"http://www.thedailyshow.com/tickets": "tds tix",
				"http://www.showclix.com/event/TheLateShowWithStephenColbert": "colbert tix",
				"http://www.interbridge.com/lineups.html#SC": "guests",
				"https://www.bluehillfarm.com/reserve/stone-barns": "^barn",
				"https://www.bluehillfarm.com/reserve/new-york": "*ny",
				"http://www.newyorkology.com/archives/calendar/index.php": "ny cal",
				"http://www.movietickets.com/house_detail.asp?house_id=7333": "bpc regal",
				"https://www.stumptowncoffee.com/brew-guides/aeropress": "aeropress",
				"http://blog.siriusxm.com/tag/alt-nation/": "alt nation"
			},
			"shop": {
				"http://ebay.com/": "ebay",
				"http://amazon.com/": "amazon",
				"http://www.bestbuy.com/": "bestbuy",
				"http://slickdeals.net/": "slickdeals",
				"http://www.directv.com/": "directv",
				"http://www.verizon.com/myverizon": "myverizon",
				"http://www.attwireless.com/": "at&t",
				"http://tec.inetbiller.com/": "teco",
				"https://www22.verizon.com/myaccount/?ID=SignIn": "verizon",
				"http://www.sprint.com/personal/wireless/manage.html": "sprint",
				"http://www.stubhub.com/the-book-of-mormon-tickets/": "^mormon", 
				"http://newyork.craigslist.org/search/sss?query=book+of+mormon&srchType=A&minAsk=&maxAsk=": "**cl"
			},
			"side": [
				"bp",
				"tnr",
				"time",
				"mlb",
				"tbl",
				"nytrng",
				"dev",
				"twitter",
				"travel",
				"apt",
				"work",
				"nyc",
				"fantasy",
				"wp",
				"js",
				"matchup"
			]
		}
	]
}