
{ "links" : {
	
	"REPOS": "",
	"page head": "https://github.com/joshbuchea/HEAD",

	"GIT": "",
	"beanstalk": "http://css-tricks.com/video-screencasts/109-getting-off-ftp-and-onto-git-deployment-with-beanstalk/",
	"guide": "http://rogerdudler.github.com/git-guide/",
	"git cheatsheet": "http://help.github.com/git-cheat-sheets/",
	"git push n pull": "http://gun.io/blog/how-to-github-fork-branch-and-pull-request/",
	"git thinkup": "http://thinkupapp.com/docs/contribute/developers/devfromsource.html",
	"git branching": "http://learn.github.com/p/branching.html",
	"git docs": "http://git-scm.com/docs",
	"git alias": "http://durdn.com/blog/2012/11/22/must-have-git-aliases-advanced-examples/",
	
	"SVN": "",
	"svn cheatsheet": "http://www.abbeyworkshop.com/howto/misc/svn01/",
	
	"iOS": "",
	"icons": "http://mathiasbynens.be/notes/touch-icons",
	
	"JS": "",
	"module": "http://www.adequatelygood.com/2010/3/JavaScript-Module-Pattern-In-Depth",
	"jsonviewer": "http://jsonviewer.stack.hu/",
	"nth child": "http://css-tricks.com/how-nth-child-works/",
	"js apps": "http://www.impressivewebs.com/javascript-resources-web-app-developers/",
	"jquery pageslide": "http://srobbin.com/jquery-plugins/pageslide/",
	"time graphs": "http://code.shutterstock.com/rickshaw/",
	"fancybox": "http://fancybox.net/",
	"js shorthand": "http://www.punkchip.com/2010/05/javascript-shorthand/",
	"json plus": "http://jsonplus.com/",
	"google async loading": "https://developers.google.com/analytics/devguides/collection/gajs/asyncTracking",
	"lazy loading": "http://friendlybit.com/js/lazy-loading-asyncronous-javascript/",
	"inteligist": "http://srobbin.com/jquery-plugins/intelligist/",
	"feature detection": "http://detector.dmolsen.com/",
	"google doc json codes": "http://blog.ouseful.info/2011/09/07/google-spreadsheets-api-listing-individual-spreadsheet-sheets-in-r/",
	"jsonp with callback": "http://javascriptweblog.wordpress.com/2010/11/29/json-and-jsonp/",
	"jsonlint": "http://jsonlint.com/",
	"jsonbeautifier": "http://jsbeautifier.org/",
	"leak finder": "https://code.google.com/p/leak-finder-for-javascript/",
	"date picker": "http://www.dangrossman.info/2012/08/20/a-date-range-picker-for-twitter-bootstrap/",
	"jquery funds": "http://jqfundamentals.com/",
	"oo js": "http://killdream.github.com/blog/2011/10/understanding-javascript-oop/",
	"front end tools": "http://www.catswhocode.com/blog/awesome-web-tools-to-simplify-front-end-development",
	"measure speed": "http://blog.trasatti.it/2012/12/measuring-the-speed-of-resource-loading-with-javascript-and-html5.html",
	"js a/b testing": "http://www.webappers.com/2012/12/27/ab-testing-using-pure-javascript-google-analytics/",
	"parallax scrolling": "https://github.com/Prinzhorn/skrollr",
	
	"html5": "",
	"html5 bookmarks": "http://html5bookmarks.com/",
	"offline storage": "http://www.thomashardy.me.uk/using-html5-localstorage-on-a-form",
	"drag drop upload": "http://html5doctor.com/drag-and-drop-to-server/",
	"fusion charts": "http://www.fusioncharts.com/?BS=AboutMenuLink",
	"html5can": "http://www.netmagazine.com/features/five-things-you-didnt-know-web-could-do",
	"html5mobiledev": "http://skookum.com/blog/20-html5-mobile-app-development-tips/",
	"app cache": "http://www.alistapart.com/articles/application-cache-is-a-douchebag/",

	"Mobile": "",
	"resources": "http://mobilewebbestpractices.com/resources/",
	"sizes": "http://www.benjaminkeen.com/misc/bricss/",
	"responsive 5 guide": "http://www.netmagazine.com/tutorials/building-fast-and-responsive-websites",
	"conditional loading": "http://blog.grayghostvisuals.com/modernizr/conditionally-loading-resources/",
	"ish": "http://bradfrostweb.com/demo/ish/",

	"CSS": "",
	"buttons": "http://www.uiparade.com/wp-content/themes/artiste/live-tools/index.html#",
	"webkit": "http://www.webmonkey.com/2012/02/webkit-isnt-breaking-the-web-you-are/",
	"preprocessing": "http://css-tricks.com/musings-on-preprocessing/",
	"floats": "http://www.onderhond.com/blog/work/mutlilevel-floats-how-to",
	"prefix": "http://codepo8.github.com/prefix-the-web/",
	"fluid img": "http://unstoppablerobotninja.com/entry/fluid-images/",
	"css-tricks": "http://css-tricks.com/",
	"box shadow": "http://box-shadow.info/",
	"less": "http://www.developerdrive.com/2012/04/learning-less-an-introduction/",
	"more less": "http://www.developerdrive.com/2012/05/learning-less-variables/",
	"multi column lists": "http://www.alistapart.com/articles/multicolumnlists/",
	"arrows": "http://cssarrowplease.com/",
	"css queries": "http://bricss.net/post/22198838298/easily-checking-in-javascript-if-a-css-media-query-has",
	"bootstrap tut": "http://www.1stwebdesigner.com/tutorials/bootstrap-your-application-using-twitter-bootstrap/",
	"web inspector": "https://github.com/subtleGradient/StandaloneWebInspector.app",
	"learn less": "http://www.developerdrive.com/2012/04/learning-less-an-introduction/",
	"circle": "http://tympanus.net/Tutorials/CircleHoverEffects/index4.html",
	"responsive patterns": "http://bradfrost.github.com/this-is-responsive/patterns.html",
	"atmedia.info": "http://atmedia.info/",
	
	"Responsive": "",
	"patterns": "http://designshack.net/articles/css/5-really-useful-responsive-web-design-patterns/",
	"resp images": "http://css-tricks.com/which-responsive-images-solution-should-you-use/",
	"fitvidjs": "http://fitvidsjs.com/",
	"frost talk": "http://www.besquare.me/session/for-a-future-friendly-web/",
	"frost": "http://bradfrost.github.com/this-is-responsive/resources.html",
	"retina query": "http://www.brettjankord.com/2012/11/28/cross-browser-retinahigh-resolution-media-queries/",
	"retina resolution": "http://blog.netvlies.nl/design-interactie/retina-revolution/",
	"responsive type": "http://webexpedition18.com/articles/responsive-typography/",
	"php device detect": "http://www.webresourcesdepot.com/php-class-for-mobile-device-detection-mobile_detect/",
	"responsive tools": "http://responsivetools.com/site-url/tnr.com/",

	"Dev": "",
	"jsfiddle": "http://jsfiddle.net/",
	"codepad": "http://codepad.org/",
	"google playground": "http://code.google.com/apis/ajax/playground/",
	"fb og debugger": "https://developers.facebook.com/tools/debug",
	"twitter card debugger": "https://dev.twitter.com/docs/cards/preview",
	"initializr": "http://www.initializr.com/",
	"html5 plate": "http://html5boilerplate.com/",
	"treehouse": "http://teamtreehouse.com/",
	"codeacademy": "http://www.codecademy.com",
	"udemy": "http://www.udemy.com/",
	"codekit": "http://incident57.com/codekit/",
	"mircodata": "http://www.w3.org/TR/html5/microdata.html",
	"betterthangrep": "http://betterthangrep.com/",
	"stripe": "https://stripe.com/",
	"snippets": "http://www.catswhocode.com/blog/awesome-sites-to-find-useful-code-snippets",
	"udacity": "http://www.udacity.com/",
	"baseline": "http://rmurphey.com/blog/2012/04/12/a-baseline-for-front-end-developers/",
	"questions": "http://darcyclarke.me/development/front-end-job-interview-questions/",
	"chrome shortcuts": "http://anti-code.com/devtools-cheatsheet/",
	"wireframe": "http://wireframe.cc/",
	"regexper": "http://www.regexper.com/",

	"Regex": "",
	"js regex": "http://www.regular-expressions.info/javascriptexample.html",
	"php regex": "http://regex.larsolavtorvik.com/",

	"BB-BS": "",
	"sample": "http://coenraets.org/blog/2012/02/sample-app-with-backbone-js-and-twitter-bootstrap/",
	"directory": "http://coenraets.org/directory/",

	"Design": "",
	"collor": "http://colllor.com/",
	"subtlepatterns": "http://subtlepatterns.com/",
	"bg masking": "http://www.webdesign.org/photoshop/photoshop-basics/the-erase-background-tool.14857.html",
	"fonts deeper": "http://thenextweb.com/dd/2012/05/02/im-done-with-helvetica-body-type/",
	"fireworks": "http://fireworks.smashingmagazine.com/2012/05/07/refining-designs-adobe-fireworks/",
	"resp toolkit": "http://smashinghub.com/ultimate-responsive-web-design-toolkit.htm",
	"kern": "http://www.paper-leaf.com/blog/2012/05/how-to-kern-properly-essential-tips-resources/",

	"Apache": "",
	"ubuntu 10.4": "http://www.howtoforge.com/ubuntu_lamp_for_newbies",
	"backups": "http://blog.asmallorange.com/procure-and-maintain-backups-with-your-lamp-webhost/",
	"secure": "http://www.petefreitag.com/item/505.cfm",
	"mysql yser": "http://www.codeunit.co.za/2011/01/17/ubuntu-how-to-create-a-mysql-user-account-via-the-terminal/",
	"mosh": "http://mosh.mit.edu/",
	"vim": "http://www.tuxfiles.org/linuxhelp/vimcheat.html",
	"bash": "http://linuxconfig.org/Bash_prompt_basics",
	"bash one liners": "http://www.catonmat.net/blog/bash-one-liners-explained-part-five/",
	"mysql command": "http://www.pantz.org/software/mysql/mysqlcommands.html",

	"PHP": "",
	"serialize": "http://blog.tanist.co.uk/files/unserialize/index.php",
	"securing": "http://www.haveyougotwoods.ca/2009/07/03/securing-php",
	"shorthand": "http://designerfoo.com/php-shorthand-php-alternative-alternate-syntax-a-quickie.html",
	"isset vs empty": "http://techtalk.virendrachandak.com/php-isset-vs-empty-vs-is_null/",
	
	"WP": "",
	"ajax scroll": "http://wp.tutsplus.com/tutorials/theme-development/how-to-create-infinite-scroll-pagination/",
	"a/b test": "http://designfestival.com/strengthen-your-website-with-simple-multivariate-testing-for-wordpress/",
	"htaccess": "http://www.netmagazine.com/tutorials/protect-your-wordpress-site-htaccess",
	"search customs": "http://www.deluxeblogtips.com/2012/04/search-all-custom-fields.html",
	"cat functions": "http://perishablepress.com/category-functions-wordpress/",
	"wp snippets": "http://www.paulund.co.uk/11-steps-to-speed-up-your-wordpress-site",
	"wp responsive images": "http://viewportindustries.com/blog/automatic-responsive-images-in-wordpress/",
	"wp meta boxes": "http://viewportindustries.com/blog/simple-but-useful-wordpress-meta-boxes/",
	"wp galleries": "http://wp.tutsplus.com/tutorials/creative-coding/image-gallery-with-custom-sized-images-bonus-jquery-plugin/",
	"svn": "http://codex.wordpress.org/Using_Subversion",
	"harden": "http://www.wptavern.com/top-5-wordpress-security-tips-you-most-likely-dont-follow",
	"wp nyc videos": "http://www.youtube.com/user/wordpressnyc",
	"wp generator": "http://generatewp.com/",
	"tools": "http://wycks.github.com/WordPress-Gear/",
		
	"Fonts": "",
	"emigre": "http://www.emigre.com/WebFonts",
	"identifont": "http://www.identifont.com/",
	
	"Speed": "",
	"speed up 1": "http://www.webdesignerdepot.com/2012/05/how-to-speed-up-your-website/",
	"yahoo best practices": "http://developer.yahoo.com/performance/rules.html#expires",
	
	"Email": "",
	"responsive email": "http://www.emaildesignreview.com/email-design-best-practice/rethinking-mobile-email-design-1331/",
	"responsive email2": "http://marketingland.com/learning-by-example-9-more-responsive-emails-25864?utm_campaign=tweet&utm_source=socialflow&utm_medium=twitter",
	"Ruby": "http://blog.tddium.com/2012/11/20/profiling-ruby/",
	
	"Other": "",
	"html archive": "http://httparchive.org/",
	"unblockus": "http://unblock-us.com/",
	
	"Shortcuts": "",
	"Google Docs": "http://support.google.com/docs/bin/answer.py?hl=en-GB&answer=181110"
	}
}
