{"links" : {
	"mail": "https://bammail.mlb.com/owa/",
	"homebase": "https://homebase.mlbcontrol.net/actions/login.do?target=%2F",
	"edi": "https://mlb.e-dialog.com/",
	"beta cookie": "http://partner.mlb.com/setBetaCookie.html",
	"wiki": "https://wiki.mlbam.com/display/MP/Home",
	"bugzilla": "http://bugzilla.mlbam.com/query.cgi",
	"FB like": "http://mlb.ed4.net/like/admin/login.cfm?c=52857911",
	"newsroom": "http://newsroom.mlbcontrol.net/user/login.mhtml?target_page=%2findex.mhtml%3f",
	"promos": "https://bamutil.mlb.com/ticketing-admin/login.jsp",
	"buttons": "http://beta.mlb.com/test/buttons/index.jsp?c_id=nym",
	"wap beta": "http://wapb.mlb.com/",
	"trac": "http://trac.mlbam.com/login",
	"pressbox": "http://pressbox.mlb.com/pressbox_open/",
	"style guide": "http://www.mlbstyleguide.com/",
	"NYM style": "https://wiki.mlbam.com/display/styleguide/Clubs#Clubs-NewYorkMets",
	
	"AL": "",
	"ANA": "http://losangeles.angels.mlb.com/index.jsp?c_id=ana",
	"BAL": "http://baltimore.orioles.mlb.com/index.jsp?c_id=bal",
	"BOS": "http://boston.redsox.mlb.com/index.jsp?c_id=bos",
	"CWS": "http://chicago.whitesox.mlb.com/index.jsp?c_id=cws",
	"CLE": "http://cleveland.indians.mlb.com/index.jsp?c_id=cle",
	"DET": "http://detroit.tigers.mlb.com/index.jsp?c_id=det",
	"KC": "http://kansascity.royals.mlb.com/index.jsp?c_id=kc",
	"MIN": "http://minnesota.twins.mlb.com/index.jsp?c_id=min",
	"NYY": "http://newyork.yankees.mlb.com/index.jsp?c_id=nyy",
	"OAK": "http://oakland.athletics.mlb.com/index.jsp?c_id=oak",
	"SEA": "http://seattle.mariners.mlb.com/index.jsp?c_id=sea",
	"TB": "http://tampabay.rays.mlb.com/index.jsp?c_id=tb",
	"TEX": "http://texas.rangers.mlb.com/index.jsp?c_id=tex",
	"TOR": "http://toronto.bluejays.mlb.com/index.jsp?c_id=tor",
	"NL": "",
	"ARI": "http://arizona.diamondbacks.mlb.com/index.jsp?c_id=ari",
	"ATL": "http://atlanta.braves.mlb.com/index.jsp?c_id=atl",
	"CHC": "http://chicago.cubs.mlb.com/index.jsp?c_id=chc",
	"CIN": "http://cincinnati.reds.mlb.com/index.jsp?c_id=cin",
	"COL": "http://colorado.rockies.mlb.com/index.jsp?c_id=col",
	"HOU": "http://houston.astros.mlb.com/index.jsp?c_id=hou",
	"LA": "http://losangeles.dodgers.mlb.com/index.jsp?c_id=la",
	"MIA": "http://miami.marlins.mlb.com/index.jsp?c_id=mia",
	"MIL": "http://milwaukee.brewers.mlb.com/index.jsp?c_id=mil",
	"NYM": "http://newyork.mets.mlb.com/index.jsp?c_id=nym",
	"PHI": "http://philadelphia.phillies.mlb.com/index.jsp?c_id=phi",
	"PIT": "http://pittsburgh.pirates.mlb.com/index.jsp?c_id=pit",
	"STL": "http://stlouis.cardinals.mlb.com/index.jsp?c_id=stl",
	"SD": "http://sandiego.padres.mlb.com/index.jsp?c_id=sd",
	"SF": "http://sanfrancisco.giants.mlb.com/index.jsp?c_id=sf",
	"WAS": "http://washington.nationals.mlb.com/index.jsp?c_id=was"
	}
}
