{ "links" : {
	"nytrng": "http://www.nytrng.com/nytrng/newspapers.htm",
	"full": "http://nytco.com/company/business_units/additional_sites.html#regional_media_group",
	"owa": "https://connect.nytco.com/",

	"salesforce": "https://www.salesforce.com/login.jsp",
	"saxotech": "http://support.saxotech.com/download/F7925F3BD8/Online/Tags/Online_Tags_605b2/",
	"nytwiki": "http://nytrmg.wik.is/",
	"wiki2": "https://nytrmg.onconfluence.com/",
	"wiki2 pass": "https://nytrmg.onconfluence.com/display/DEV/Server+Info+and+logins",

	"jira ": "https://nytrmg.onjira.com/secure/ViewProfile.jspa",
	"jire order": "https://nytrmg.onjira.com/secure/IssueNavigator.jspa?sorter/field=status&sorter/order=ASC",
	"wrappers": "http://lldev.ny.atl.publicus.com/apps/pbcs.dll/section?template=makewrap2",
	"nyadmin": "http://nyadmin.ny.atl.publicus.com/edit",

	"sites": "",
	"HT": "http://www.blueridgenow.com/",
	"DC": "http://www.dailycomet.com/",
	"LD": "http://www.the-dispatch.com/",
	"GD": "http://www.gadsdentimes.com/",
	"GS": "http://www.gainesville.com/",
	"GX": "http://www.gatorsports.com/",
	"SJ": "http://www.goupstate.com/",
	"HT": "http://www.heraldtribune.com/",
	"HC": "http://www.houmatoday.com/",
	"LL": "http://www.theledger.com/",
	"OS": "http://www.ocala.com/",
	"SR": "http://www.pressdemocrat.com/",
	"TR": "http://www.telegram.com/",
	"GT": "http://www.timesdaily.com/",
	"TX": "http://www.tidesports.com/",
	"TL": "http://www.tuscaloosanews.com/",
	"TM": "http://www.tuskmag.com/",
	"WM": "http://www.wilmingtonstar.com/",
	"NYTI": "http://www.nytimes-institute.com/", 
	
	"blogs": "",
	"b- GT": "http://blogs.gadsdentimes.com/wp-admin",
	"b- HC": "http://blogs.houmatoday.com/wp-admin",
	"b- DC": "http://blogs.dailycomet.com/wp-admin",
	"b- GS": "http://blogs.gainesville.com/wp-admin",
	"b- HT": "http://blogs.blueridgenow.com/wp-admin",
	"b- LD": "http://blogs.the-dispatch.com/wp-admin",
	"b- LL": "http://blogs.theledger.com/wp-admin",
	"b- OS": "http://blogs.ocala.com/wp-admin",
	"b- SH": "http://blogs.heraldtribune.com/wp-admin",
	"b- SJ": "http://blogs.goupstate.com/wp-admin",
	"b- SR": "http://blogs.pressdemocrat.com/wp-admin",
	"b- TL": "http://blogs.tuscaloosanews.com/wp-admin",
	"b- WM": "http://blogs.starnewsonline.com/wp-admin",
	"b- WN": "http://blogs.newschief.com/wp-admin",
	"b- NBBJ": "http://northbaybusinessjournal.com/wp-admin",
	"b- NBBJb": "http://blogs.northbaybusinessjournal.com/wp-admin",
	
	"forums": "",
	"f- DC": "http://forum.dailycomet.com",
	"f- GS": "http://forum.gainesville.com",
	"f- GX": "http://forum.gatorsports.com",
	"f- GT": "http://forum.gadsdentimes.com",
	"f- HC": "http://forum.houmatoday.com",
	"f- HT": "http://forum.blueridgenow.com",
	"f- LD": "http://forum.the-dispatch.com",
	"f- OS": "http://forum.ocala.com",
	"f- SH": "http://forum.heraldtribune.com",
	"f- SHy": "http://forum.yoursarasota.com",
	"f- SJ": "http://forum.goupstate.com",
	"f- SJs": "http://forum.palmettofootballtalk.com",
	"f- SRp": "http://forum.petaluma360.com",
	"f- TL": "http://forum.tuscaloosanews.com",
	"f- TX": "http://forum.tidesports.com",
	"f- WM": "http://forum.starnewsonline.com",
	"f- WN": "http://forum.newschief.com",
	"f- NBBJ": "http://forum.northbaybusinessjournal.com",

    "employee links": "",        
	"emp-conn": "http://web.nytimes.com/xpedio/groups/system/@corp/@econnect/documents/dynamicpage/ec_home.hcst",
	"nytco": "http://nytco.com/",
	"selfservice": "http://selfservice.nytssc.com/",
	"ssc": "http://www.ssc.nytimes.com/",
	"intranet": "http://web.nytimes.com/xpedio/groups/public/@insite/documents/dynamicpage/insite.hcst",
	"nyt-notes": "http://nyt-notes-11.nytimes.com/perfmgmt/nytpmsite.nsf/site.jsp",
	"nyt insite new intranet": "http://web.nytimes.com/insite",
	"inotes": "http://inotes.nytssc.com/redirect.nsf",
	"lotus web": "http://inotes.nytssc.com/redirect.nsf"

	}
}
