
{ "links" : {
	"DEV": "",
	"Trello": "https://trello.com/",
	"github alley": "https://github.com/alleyinteractive/tnr",
	"github tnr": "https://github.com/newrepublic?tab=repositories",
	"github stage": "https://github.com/alleyinteractive/tnr/tree/staging",
	"local dev": "http://newrepublic.dev",
	"staging": "http://staging-tnr.gotpantheon.com/",
	"/latest": "http://www.newrepublic.com/latest",
	"twitter cards": "https://dev.twitter.com/docs/cards/validation/validator",
	"fb url lint": "https://developers.facebook.com/tools/debug/og/object",
	"google rich snippets": "http://www.google.com/webmasters/tools/richsnippets",

	"NEWS": "",
	"tnr": "http://tnr.com",
	"glimpse": "https://dash.parsely.com/tnr.com/glimpse",
	"digg": "http://digg.com/",
	"longform": "http://longform.org/",
	"upworthy": "http://upworthy.com",
	"readability": "http://www.readability.com/top-reads/",
	"rt.ly": "http://rt.ly/#d=tnr.com",
	"media alerts": "https://groups.google.com/forum/#!forum/google-media-updates",

	"RESOURCE": "",
	"google videos": "http://www.youtube.com/user/GoogleWebmasterHelp",
	"reader": "http://www.google.com/reader/view/#stream/user%2F18305779273755753157%2Flabel%2FNew%20Feeds",
	"newsdiffs": "http://www.newsdiffs.org/press/",
	"netmarket": "http://www.netmarketshare.com/",
	
	"TOOLS": "",
	"utm": "http://support.google.com/analytics/bin/answer.py?hl=en&answer=1033867",
	"gcal": "http://support.google.com/calendar/bin/answer.py?hl=en&answer=1186917",
	"digg sumbit": "http://digg.com/submit",
	"bit.ly": "http://bit.ly",
	"chartbeat": "http://chartbeat.com/",
	"analytics": "http://www.google.com/analytics/",
	"adx": "https://www.google.com/adxseller/adx/app#home",
	"parsely": "https://dash.parsely.com/tnr.com/",
	"google tools": "https://www.google.com/webmasters/tools/home?hl=en",
	"vimeo": "https://vimeo.com/settings/upgrade",
	"ga url builder": "http://support.google.com/analytics/bin/answer.py?hl=en&answer=1033867",
	"adobe api": "http://www.adobe.com/devnet-docs/digitalpublishingsuite/LibraryAndStoreSDK-2.27/docs/symbols/adobeDPS.html",
	
	"SOCIAL": "",
	"fb": "https://www.facebook.com/thenewrepublic",
	"twitter": "https://twitter.com/tnr",
	"gplus": "https://plus.google.com/+thenewrepublic/",
		
	"ADMIN": "",
	"dyn": "https://manage.dynect.net/",
	"cds": "http://www.mycdsglobal.com/",
	"sailthru": "https://my.sailthru.com/",
	"teads": "http://manager.teads.tv/",
	"redmine": "https://work.alley.ws/projects/tnr/issues?sort=updated_on%3Adesc%2Cid%3Adesc",	
	"itunes": "https://itunesconnect.apple.com/",
	"adobe": "digitalpublishing.acrobat.com",
	"esp": "https://www.pubservice.com/login.aspx",
	"hubspot": "https://app.hubspot.com/contacts/248084/",
	"sprout": "https://sproutsocial.com/",
	"livefyre": "www.livefyre.com/admin/",
	"livefyre admin": "http://www.livefyre.com/v3/site/341330/",
	"liveball": "https://tnr.postclickmarketing.com/Admin/Login.aspx",
	"nook": "https://partnerreporting.barnesandnoble.com/dashboard/",
	"kindle": "https://kindlepublishing.amazon.com/gp/vendor/sign-in/176-8472669-6327349",
	"play": "https://www.google.com/producer/feature/enable?feature=magazines,repub,ofip",
	"cafepress": "http://members.cafepress.com/stores/customize_prem.aspx",
	"mailchimp": "https://us1.admin.mailchimp.com/",
	"jjomedia": "https://jjomedia.basecamphq.com/",
	"optimizely": "https://www.optimizely.com/dashboard",
	"wufoo": "https://secure.wufoo.com/login/",
	"nac": "https://www.nac.net/customercare.asp",
	"webnames": "https://www.webnames.ca/",
	"digicert": "http://www.digicert.com/",
	"sub page": "https://www.pubservice.com/tnr/Subnew.aspx?pk=M2CHTPA",
	"admin": "http://www.tnr.com/user/login",
	"home promo": "http://www.tnr.com/admin/build/block/configure/custom_blocks/homepage_promo",
	"content overlay": "http://www.tnr.com/admin/settings/content_overlay",
	"old tnr site": "http://hcs.tnr",
	"tnr.com": "http://tnr.com"
	}
}
